name: crm-automation

services:
  postgres:
    image: postgres:18.6
    container_name: crm_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-crm_backend}
      N8N_DB_NAME: ${N8N_DB_NAME:-crm_db}

    ports:
      - '${DB_PORT:-5432}:5432'

    volumes:
      - pgdata:/var/lib/postgresql
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-crm_backend}']
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4.3.6-management-alpine
    container_name: crm_rabbitmq
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}

    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_DEFAULT_PORT:-15672}:15672'

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: crm_n8n
    restart: unless-stopped

    ports:
      - '${N8N_PORTS:-5678}:5678'

    environment:
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh # Định múi giờ cho các node Schedule/Cron trong Workflow
      - TZ=Asia/Ho_Chi_Minh

      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME:-crm_db}
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${DB_USER:-postgres}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD:-postgres}
      - N8N_BASIC_AUTH_ACTIVE=false

      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-pro}
      - BACKEND_INTERNAL_URL=${BACKEND_INTERNAL_URL:-http://host.docker.internal:3000}
      - N8N_API_KEY=${N8N_API_KEY}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  pgdata:
  rabbitmq_data:
  n8n_data:
